#!/bin/sh

/usr/bin/invoke_app "$@" -t smiletest \
 -u wrwroxy-0.1 \
 -u node-6.11.2 \
 -u python3.4 \
 -w "none" \
 -c "xview -fullscreen -onroot @tool/www/public/bootstrap/img/logo/smile-logos/small-logo3.png" \
 -c "wrwroxy --stream-log --logfile /dev/null --loglevel DEBUG" \
 -c "node @tool/www/graphql/bin/www" \
 -C "node @tool/www/app.js"


